### ISSUE TITLE
unable to activate plugin

### ISSUE THREAD

**Issue by ehamon** [mjschwartz/WPGmappity#1]
My wordpress blog isn't on the root directory. When activating the plugin, i have:
"
Warning: require_once() [function.require-once]: open_basedir restriction in effect. File(/wpgmappity-admin.php) is not within the allowed path(s): (/mnt/164/sda/1/d/WWWWW) in /mnt/164/sda/1/d/WWWW/tenjinkai/wp-content/plugins/wpgmappity/wpgmappity.php  on line 49
"

Hosted on 'free.fr'. (php restrictions)
Regards

**Comment by ehamon** [comment]
Found:
'Free' uses 'safe_mode' in their 'php.ini' configuration. Could not turn it off. The current plugin WPGmappity could not be run on this provider hosting.
Regards

**Comment by mjschwartz** [comment]
Sorry for the delay.

Patches a problem with the pathing of the includes that was trippin gup some hosts.

**Comment by ehamon** [comment]
Thank you very much . Works great now on 'free.fr' hosting.
